version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install fake-cli -g
  - dotnet tool install coverlet.console -g
  - choco install codecov --no-progress --confirm
  - choco install gitversion.portable --no-progress --confirm
  - git submodule update --init
  - nuget restore
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '.fake -> Build.fsx'
before_build:
  - ps: gitversion /output buildserver 
build_script:
- ps: >-
    fake build --parallel 4
test: off
deploy:
- provider: Environment
  name: GitHub
  on:
    APPVEYOR_REPO_TAG: true