version: 1.0.{build}
image: Visual Studio 2017
install:
  - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
  - choco install dotnetcore-sdk --version 3.0.100-preview9-014004 --pre 
  - choco install codecov --no-progress --confirm
  - choco install gitversion.portable --no-progress --confirm
  - npm install -g semantic-release @semantic-release/changelog @semantic-release/git
cache:
  - '%LOCALAPPDATA%\Temp\Chocolatey -> appveyor.yml'
  - 'packages\cache -> paket.*'
before_build:
  - ps: gitversion /output buildserver 
build_script:
- ps: |
    [System.Environment]::SetEnvironmentVariable("SonOfPicasso_Verbose", "true")
    .\build.ps1
    codecov -f reports\SonOfPicasso.Core.Tests.opencover.xml --flag coretest
    codecov -f reports\SonOfPicasso.Data.Tests.opencover.xml --flag datatest
    codecov -f reports\SonOfPicasso.UI.Tests.opencover.xml --flag uitest
    codecov -f reports\SonOfPicasso.Integration.Tests.opencover.xml --flag integration
    codecov -f reports\SonOfPicasso.Tools.Tests.opencover.xml --flag tools 
test: off
deploy_script: semantic-release