name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup GitVersion
      uses: StanleyGoldmab/setup-gitversion@v1
    - name: Install Fake Cli
      run: dotnet tool install fake-cli -g

# version: 1.0.{build}
# image: Visual Studio 2017
# install:
#   - dotnet tool install fake-cli -g
#   - dotnet tool install coverlet.console -g
#   - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
#   - choco install dotnetcore-sdk --version 3.0.100-preview9-014004 --pre 
#   - choco install codecov --no-progress --confirm
#   - choco install gitversion.portable --no-progress --confirm
#   - npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
# cache:
#   - '%LOCALAPPDATA%\Temp\Chocolatey -> appveyor.yml'
#   - '.fake -> Build.fsx'
#   - 'packages\cache -> paket.*'
# before_build:
#   - ps: gitversion /output buildserver 
# build_script:
# - ps: >-
#     fake build --parallel 4
# test: off
# deploy_script: semantic-release