name: Build and Test
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      SonOfPicasso_Verbose: True
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install Semantic Release Tools
      run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
    - name: Build
      run: .\build.ps1
    - name: Upload SonOfPicasso.Core.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Core.Tests.opencover.xml
        flags: coretests
    - name: Upload SonOfPicasso.Data.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Data.Tests.opencover.xml
        flags: datatests
    - name: Upload SonOfPicasso.UI.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.UI.Tests.opencover.xml
        flags: uitests
    - name: Upload SonOfPicasso.Integration.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Integration.Tests.opencover.xml
        flags: integration
    - name: Upload SonOfPicasso.Tools.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Tools.Tests.opencover.xml
        flags: tools
    - name: Semantic Release
      run: semantic-release    
