name: Build and Test
on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      SonOfPicasso_Verbose: True
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build and Test
      run: |
        .\build.ps1
        try {
          .\test.ps1
        }
        catch {
          echo "set-env name=test_exit_code::1"
          echo "::set-env name=test_exit_code::1"
        }
        7z a reports.zip reports\*
    - name: Upload Build Log
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build
        path: build.log
    - name: Upload Reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reports
        path: reports.zip
    - name: Upload SonOfPicasso.Core.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Core.Tests.opencover.xml
        flags: coretests
    - name: Upload SonOfPicasso.Data.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Data.Tests.opencover.xml
        flags: datatests
    - name: Upload SonOfPicasso.UI.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.UI.Tests.opencover.xml
        flags: uitests
    - name: Upload SonOfPicasso.Integration.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Integration.Tests.opencover.xml
        flags: integration
    - name: Upload SonOfPicasso.Tools.Tests to CodeCov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Tools.Tests.opencover.xml
        flags: tools
    - name: Handle test result
      run: exit $env:test_exit_code
