name: Build and Test
on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup GitVersion
      uses: StanleyGoldman/setup-gitversion@v1.0.0
      with:
          gitversion-version: 5.x
    - name: Install other tools
      run: |- 
        sudo npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
    - name: GitVersion 
      run: |-
        GitVersion /updateassemblyinfo ./src/common/SharedAssemblyInfo.cs /ensureassemblyinfo
        cat ./src/common/SharedAssemblyInfo.cs
        sed -i -E "s/AssemblyFileVersion\(\"(.*?)\"\)/AssemblyFileVersion(\"\1.0\")/" ./src/common/SharedAssemblyInfo.cs
        sed -i -E "s/AssemblyVersion\(\"(.*?)\"\)/AssemblyVersion(\"\1.0\")/" ./src/common/SharedAssemblyInfo.cs
        sed -i -E "s/AssemblyInformationalVersion\(\"(.*?)\"\)/AssemblyInformationalVersion(\"\1.0\")/" ./src/common/SharedAssemblyInfo.cs
        cat ./src/common/SharedAssemblyInfo.cs
    - name: Run
      run: |-
        env

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup GitVersion
      uses: StanleyGoldman/setup-gitversion@v1.0.0
      with:
          gitversion-version: 5.x
    - name: Install other tools
      run: |- 
        sudo npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
    - name: GitVersion 
      run: GitVersion /updateassemblyinfo ./src/common/SharedAssemblyInfo.cs /ensureassemblyinfo
    - name: Run
      run: env

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install other tools
      run: |- 
        npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
    - name: GitVersion 
      run: GitVersion /updateassemblyinfo src\common\SharedAssemblyInfo.cs /ensureassemblyinfo
    - name: Run
      run: |- 
        Get-ChildItem Env:

      

# deploy_script: semantic-release
