name: Build and Test
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install Coverlet
      run: dotnet tool install coverlet.console -g
    - name: Install Codecov
      run: choco install codecov --no-progress --confirm
    - name: Install Semantic Release Tools
      run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli
    - name: GitVersion
      run: GitVersion /updateassemblyinfo src\common\SharedAssemblyInfo.cs /ensureassemblyinfo /output BuildServer
    - name: Build
      run: dotnet build SonOfPicasso.sln --configuration "Release"
    - name: Test SonOfPicasso.Tools.Tests
      run: |-
        dotnet test src\SonOfPicasso.Tools.Tests\SonOfPicasso.Tools.Tests.csproj `
          --logger "trx;LogFileName=SonOfPicasso.Tools.Tests-netcoreapp3.0.results.trx" `
          --configuration "Release" `
          --results-directory "../../reports"
    - name: Semantic Release
      run: semantic-release
      
