name: Build and Test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: |
        dotnet publish -c Release .\SonOfPicasso.sln -fl -flp:logfile=build.log -flp:verbosity=detailed
    - name: Test - SonOfPicasso.Core
      if: always()
      env:
        SonOfPicasso_Verbose: True
      run: |
        .\test.ps1 "SonOfPicasso.Core.Tests"
    - name: Test - SonOfPicasso.Data
      if: always()
      env:
        SonOfPicasso_Verbose: True
      run: |
        .\test.ps1 "SonOfPicasso.Data.Tests"
    - name: Test - SonOfPicasso.Integration
      if: always()
      env:
        SonOfPicasso_Verbose: True
      run: |
        .\test.ps1 "SonOfPicasso.Integration.Tests"
    - name: Test - SonOfPicasso.UI
      if: always()
      env:
        SonOfPicasso_Verbose: True
      run: |
        .\test.ps1 "SonOfPicasso.UI.Tests"
    - name: Test - SonOfPicasso.Tools
      if: always()
      env:
        SonOfPicasso_Verbose: True
      run: |
        .\test.ps1 "SonOfPicasso.Tools.Tests"
    - name: Test Cleanup
      if: always()
      run: |
        gci -Path .\reports\ -Directory | rm -Recurse
    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build
        path: build.log
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reports
        path: reports
    - name: Upload SonOfPicasso.Core.Tests to CodeCov
      if: always()
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Core.Tests.opencover.xml
        flags: coretests
    - name: Upload SonOfPicasso.Data.Tests to CodeCov
      if: always()
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Data.Tests.opencover.xml
        flags: datatests
    - name: Upload SonOfPicasso.UI.Tests to CodeCov
      if: always()
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.UI.Tests.opencover.xml
        flags: uitests
    - name: Upload SonOfPicasso.Integration.Tests to CodeCov
      if: always()
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Integration.Tests.opencover.xml
        flags: integration
    - name: Upload SonOfPicasso.Tools.Tests to CodeCov
      if: always()
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: reports\SonOfPicasso.Tools.Tests.opencover.xml
        flags: tools
