name: Build and Test
on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup GitVersion
      uses: StanleyGoldman/setup-gitversion@master
      with:
          gitversion-version: 5.x
    - name: Install other tools
      run: |-
        dotnet tool install fake-cli -g
        dotnet tool install coverlet.console -g
        sudo npm install -g semantic-release @semantic-release/changelog @semantic-release/git commit-analyzer-cli

# before_build:
#   - ps: gitversion /output buildserver 
# build_script:
# - ps: >-
#     fake build --parallel 4
# test: off
# deploy_script: semantic-release
